import type { ChatPreferences, Profile } from './types';

export const SHEET_COLUMN_HEADERS = [
  'exportedAt',
  'fullName',
  'gender',
  'pronouns',
  'email',
  'whatsappNumber',
  'location',
  'academicStatus',
  'degreeType',
  'yearOfStudy',
  'graduationYear',
  'topLevelCategory',
  'specializationCategory',
  'customCategory',
  'specialization',
  'customSpecialization',
  'collegeName',
  'cgpa',
  'subjectSkills',
  'toolSkills',
  'aiSkills',
  'professionalSkills',
  'internships',
  'volunteering',
  'interests',
  'projectsJson',
  'examsJson',
  'certificationsJson',
  'aspirations_idealRole',
  'aspirations_industryInterest',
  'aspirations_higherStudies',
  'aspirations_researchInterest',
  'reflections_impactPurpose',
  'reflections_strengths',
  'reflections_curiosity',
  'reflections_grittyGrowth',
  'reflections_spark',
  'reflections_opportunities',
  'reflections_threats',
  'lastSyncedAt',
  'lastUpdatedAt',
  'chat_responseLength',
  'chat_responseFormat',
] as const;

function joinSemicolon(values: string[] | undefined): string {
  if (!values?.length) return '';
  return values.join('; ');
}

export function profileToDataframeRow(
  profile: Profile,
  chatPreferences: ChatPreferences | undefined,
  exportedAt: string
): string[] {
  const a = profile.aspirations;
  const r = profile.reflections;

  return [
    exportedAt,
    profile.fullName,
    profile.gender,
    profile.pronouns,
    profile.email,
    profile.whatsappNumber,
    profile.location,
    profile.academicStatus,
    profile.degreeType,
    profile.yearOfStudy,
    profile.graduationYear,
    profile.topLevelCategory,
    profile.specializationCategory,
    profile.customCategory,
    profile.specialization,
    profile.customSpecialization,
    profile.collegeName,
    profile.cgpa,
    joinSemicolon(profile.subjectSkills),
    joinSemicolon(profile.toolSkills),
    joinSemicolon(profile.aiSkills),
    joinSemicolon(profile.professionalSkills),
    joinSemicolon(profile.internships),
    joinSemicolon(profile.volunteering),
    joinSemicolon(profile.interests),
    JSON.stringify(profile.projects ?? []),
    JSON.stringify(profile.exams ?? []),
    JSON.stringify(profile.certifications ?? []),
    a.idealRole,
    a.industryInterest,
    String(a.higherStudies),
    String(a.researchInterest),
    r.impactPurpose,
    r.strengths,
    r.curiosity,
    r.grittyGrowth,
    r.spark,
    r.opportunities,
    r.threats,
    profile.lastSyncedAt ?? '',
    profile.lastUpdatedAt ?? '',
    chatPreferences?.responseLength ?? '',
    chatPreferences?.responseFormat ?? '',
  ].map((v) => (v === undefined || v === null ? '' : String(v)));
}
